/*
 * lvrm.h
 *
 *  Created on: 25 oct. 2022
 *      Author: Ludo
 */

#ifndef LVRM_H
#define LVRM_H

typedef enum {
	LVRM_REGISTER_ADDRESS_BOARD_ID,
	LVRM_REGISTER_ADDRESS_RS485_ADDRESS,
	LVRM_REGISTER_ADDRESS_VIN_MV,
	LVRM_REGISTER_ADDRESS_VOUT_MV,
	LVRM_REGISTER_ADDRESS_IOUT_UA,
	LVRM_REGISTER_ADDRESS_VMCU,
	LVRM_REGISTER_ADDRESS_OUT_EN,
	LVRM_REGISTER_ADDRESS_LAST,
} LVRM_register_address_t;

#endif /* LVRM_H */
