/*
 * dinfox.h
 *
 *  Created on: 12 nov 2022
 *      Author: Ludo
 */

#ifndef __DINFOX_H__
#define __DINFOX_H__

#include "node.h"
#include "string.h"
#include "types.h"

/*** DINFOX boards identifier ***/

typedef enum {
	DINFOX_BOARD_ID_LVRM = 0,
	DINFOX_BOARD_ID_BPSM,
	DINFOX_BOARD_ID_DDRM,
	DINFOX_BOARD_ID_UHFM,
	DINFOX_BOARD_ID_GPSM,
	DINFOX_BOARD_ID_SM,
	DINFOX_BOARD_ID_DIM,
	DINFOX_BOARD_ID_RRM,
	DINFOX_BOARD_ID_DMM,
	DINFOX_BOARD_ID_MPMCM,
	DINFOX_BOARD_ID_R4S8CR,
	DINFOX_BOARD_ID_LAST,
	DINFOX_BOARD_ID_ERROR
} DINFOX_board_id_t;

/*** DINFOX boards address ranges ***/

#define DINFOX_NODE_ADDRESS_RANGE_LVRM		16
#define DINFOX_NODE_ADDRESS_RANGE_BPSM		4
#define DINFOX_NODE_ADDRESS_RANGE_DDRM		16
#define DINFOX_NODE_ADDRESS_RANGE_UHFM		4
#define DINFOX_NODE_ADDRESS_RANGE_GPSM		4
#define DINFOX_NODE_ADDRESS_RANGE_SM		4
#define DINFOX_NODE_ADDRESS_RANGE_RRM		4
#define DINFOX_NODE_ADDRESS_RANGE_MPMCM		4
#define DINFOX_NODE_ADDRESS_RANGE_R4S8CR	15

typedef enum {
	DINFOX_NODE_ADDRESS_DMM = 0x00,
	DINFOX_NODE_ADDRESS_DIM = 0x01,
	DINFOX_NODE_ADDRESS_BPSM_START = 0x08,
	DINFOX_NODE_ADDRESS_UHFM_START = (DINFOX_NODE_ADDRESS_BPSM_START + DINFOX_NODE_ADDRESS_RANGE_BPSM),
	DINFOX_NODE_ADDRESS_GPSM_START = (DINFOX_NODE_ADDRESS_UHFM_START + DINFOX_NODE_ADDRESS_RANGE_UHFM),
	DINFOX_NODE_ADDRESS_SM_START = (DINFOX_NODE_ADDRESS_GPSM_START + DINFOX_NODE_ADDRESS_RANGE_GPSM),
	DINFOX_NODE_ADDRESS_RRM_START = (DINFOX_NODE_ADDRESS_SM_START + DINFOX_NODE_ADDRESS_RANGE_SM),
	DINFOX_NODE_ADDRESS_MPMCM_START = (DINFOX_NODE_ADDRESS_RRM_START + DINFOX_NODE_ADDRESS_RANGE_RRM),
	// Note: 0x20-0x2F address range is forbidden due to R4S8CR read command.
	DINFOX_NODE_ADDRESS_LVRM_START = 0x30,
	DINFOX_NODE_ADDRESS_DDRM_START = (DINFOX_NODE_ADDRESS_LVRM_START + DINFOX_NODE_ADDRESS_RANGE_LVRM),
	DINFOX_NODE_ADDRESS_LBUS_LAST = 0x6F,
	DINFOX_NODE_ADDRESS_R4S8CR_START = (DINFOX_NODE_ADDRESS_LBUS_LAST + 1),
	DINFOX_NODE_ADDRESS_BROADCAST = (DINFOX_NODE_ADDRESS_R4S8CR_START + DINFOX_NODE_ADDRESS_RANGE_R4S8CR)
} DINFOX_address_range_t;

/*** DINFOX common registers set ***/

typedef enum {
	DINFOX_REGISTER_NODE_ADDRESS = 0,
	DINFOX_REGISTER_BOARD_ID,
	DINFOX_REGISTER_HW_VERSION_MAJOR,
	DINFOX_REGISTER_HW_VERSION_MINOR,
	DINFOX_REGISTER_SW_VERSION_MAJOR,
	DINFOX_REGISTER_SW_VERSION_MINOR,
	DINFOX_REGISTER_SW_VERSION_COMMIT_INDEX,
	DINFOX_REGISTER_SW_VERSION_COMMIT_ID,
	DINFOX_REGISTER_SW_VERSION_DIRTY_FLAG,
	DINFOX_REGISTER_RESET_REASON,
	DINFOX_REGISTER_ERROR_STACK,
	DINFOX_REGISTER_TMCU_DEGREES,
	DINFOX_REGISTER_VMCU_MV,
	DINFOX_REGISTER_LAST
} DINFOX_register_address_t;

#endif /* __DINFOX_H__ */
